import React from 'react'
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Link from 'next/link'
import { Navbar } from '@/components/Navbar'


const contact = () => {
    return (
        <>
        <Head>
        <title>Contact Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
            <main className={styles.main}>
                <h1> Contact Demo</h1>
                <div>
                    <Link href="/">
                        Return Home
                    </Link>

                </div>

            </main>
        </>
    )
}

export default contact