import styles from "./Layout.module.css"
import Head from 'next/head'
import { Navbar } from "../Navbar"

export const Layout = ({ children }) => {


  return (
    <div>
      <Head>
        <title>Home Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div>
        {children}
        </div>

      </main>



    </div>
  )
}
